Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
